# Generated by Django 6.0.6 on 2026-06-07 10:05

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0019_multicurrency"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountryPrice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "country",
                    models.CharField(help_text="ISO 3166-1 alpha-2 (uppercase).", max_length=2),
                ),
                ("currency", models.CharField(max_length=3)),
                (
                    "sticker_minor",
                    models.IntegerField(
                        help_text="Tax-inclusive consumer sticker (source of truth) in currency minor units."
                    ),
                ),
                (
                    "base_minor",
                    models.IntegerField(
                        help_text="Derived tax-exclusive Stripe unit_amount in currency minor units."
                    ),
                ),
                (
                    "is_curated",
                    models.BooleanField(
                        default=False,
                        help_text="Human-curated sticker — excluded from the FX suggestion refresh.",
                    ),
                ),
                ("stripe_price_id", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan_price",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="country_prices",
                        to="billing.planprice",
                    ),
                ),
                (
                    "product_price",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="country_prices",
                        to="billing.productprice",
                    ),
                ),
            ],
            options={
                "db_table": "country_prices",
                "ordering": ("country",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("plan_price__isnull", False), ("product_price__isnull", True)
                            ),
                            models.Q(
                                ("plan_price__isnull", True), ("product_price__isnull", False)
                            ),
                            _connector="OR",
                        ),
                        name="countryprice_has_owner",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("plan_price__isnull", False)),
                        fields=("plan_price", "country"),
                        name="uniq_country_plan_price_country",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("product_price__isnull", False)),
                        fields=("product_price", "country"),
                        name="uniq_country_product_price_country",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("stripe_price_id__isnull", False)),
                        fields=("stripe_price_id",),
                        name="uniq_country_stripe_price_id",
                    ),
                ],
            },
        ),
    ]
